version: "3"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./os/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - network

  #Nginx Service
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./os/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - network

  #MySQL Service
  db:
    image: mysql:latest
    #для mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: r00t
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      # - ./os/db:/var/lib/mysql
      - ./os/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - network

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: r00t
      # PMA_ARBITRARY: 1
    depends_on:
      - db
    networks:
      - network

#Docker Networks
networks:
  network:
    driver: bridge

#Volumes
# volumes:
#   ./os/db:
#     driver: local
